### ISSUE TITLE
[Bug]: docker-compose-types = "^0.2.2" does not exists

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#17]
### What happened?

On Mac M1, using cargo 1.59.0.

When i want to install the beta branch of the lenra_cli i have an error.
The same error appear when i try to install from the repo (beta branch) using `cargo install --path .` or using the `cargo install lenra_cli` command.

It's weird because the 0.2.2 seems to exists 
https://crates.io/crates/docker-compose-types/versions

### Relevant log output

```Shell
❯ cargo install --path .
  Installing lenra_cli v0.0.0 (/Users/xxxxx/Documents/lenra/lenra_cli)
    Updating crates.io index
error: failed to compile `lenra_cli v0.0.0 (/Users/xxxxx/Documents/lenra/lenra_cli)`, intermediate artifacts can be found at `/Users/xxxxx/Documents/lenra/lenra_cli/target`

Caused by:
  failed to select a version for the requirement `docker-compose-types = "^0.2.2"`
  candidate versions found which didn't match: 0.2.1, 0.2.0, 0.1.7, ...
  location searched: crates.io index
  required by package `lenra_cli v0.0.0 (/Users/xxxxx/Documents/lenra/lenra_cli)`
```

**Comment by taorepoara** [comment]
Have you tried to install it from crates.io ?

```bash
cargo install lenra_cli@1.0.0-beta.4
```

**Comment by Nesqwik** [comment]
Yes, it does not exists...
```bash
❯ cargo install lenra_cli@1.0.0-beta.4
    Updating crates.io index
error: could not find `lenra_cli@1.0.0-beta.4` in registry `crates-io` with version `*`
❯ cargo install lenra_cli
    Updating crates.io index
error: could not find `lenra_cli` in registry `crates-io` with version `*`
```

**Comment by taorepoara** [comment]
fixed by #37

**Comment by aloner-pro** [comment]
On windows also I am facing the same problem. I wanted to contribute to `python-template` but it showing the following error.

```
C:\Users\KIIT>cargo install lenra_cli --version=1.0.0-beta.5
    Updating crates.io index
  Installing lenra_cli v1.0.0-beta.5
error: failed to compile `lenra_cli v1.0.0-beta.5`, intermediate artifacts can be found at `C:\Users\KIIT\AppData\Local\Temp\cargo-installWFd8Wg`

Caused by:
  failed to select a version for the requirement `docker-compose-types = "^0.2.2"`
  candidate versions found which didn't match: 0.2.1, 0.2.0, 0.1.7, ...
  location searched: crates.io index
  required by package `lenra_cli v1.0.0-beta.5
``` 
I also tried the other way but it too shows this error-

```
C:\Users\KIIT> cargo install lenra_cli@1.0.0-beta.5
    Updating crates.io index
error: could not find `lenra_cli@1.0.0-beta.5` in registry `crates-io` with version `*`
```

**Comment by taorepoara** [comment]
> On windows also I am facing the same problem. I wanted to contribute to `python-template` but it showing the following error.
> 
> ```
> C:\Users\KIIT>cargo install lenra_cli --version=1.0.0-beta.5
>     Updating crates.io index
>   Installing lenra_cli v1.0.0-beta.5
> error: failed to compile `lenra_cli v1.0.0-beta.5`, intermediate artifacts can be found at `C:\Users\KIIT\AppData\Local\Temp\cargo-installWFd8Wg`
> 
> Caused by:
>   failed to select a version for the requirement `docker-compose-types = "^0.2.2"`
>   candidate versions found which didn't match: 0.2.1, 0.2.0, 0.1.7, ...
>   location searched: crates.io index
>   required by package `lenra_cli v1.0.0-beta.5
> ```
> 
> I also tried the other way but it too shows this error-
> 
> ```
> C:\Users\KIIT> cargo install lenra_cli@1.0.0-beta.5
>     Updating crates.io index
> error: could not find `lenra_cli@1.0.0-beta.5` in registry `crates-io` with version `*`
> ```

Hi,
Can you try to get the [latest version of the our CLI](https://github.com/lenra-io/lenra_cli/releases/tag/v1.0.0-beta.8). This problem should be fixed.

**Comment by aloner-pro** [comment]
> > On windows also I am facing the same problem. I wanted to contribute to `python-template` but it showing the following error.
> 
> Upgrading cargo to the latest version fixed the issue for me !

This worked
