### ISSUE TITLE
[change in the welcoming mail] 

### ISSUE THREAD

**Issue by Alienor-Lenra** [lenra-io/lenra_cli#178]
![Capture d’écran 2023-01-31 à 10 25 37](https://user-images.githubusercontent.com/102291723/215720816-9f119860-dfda-4d66-8af1-69e13b877152.png)

when a dev receives the mail that welcomes him/her for registration,  change the sender from "contact@lenra.io" to "Len at Lenra" cf screenshot

**Comment by jonas-martinez** [comment]
Linked to https://github.com/lenra-io/lenra_cli/discussions/106
