### ISSUE TITLE
[EPIC] App Navigation

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#181]
## Current Behavior

Currently, there is no navigation system in the applications, this means that when using an app, if you accidentally press ENTER, it will exit the app no matter where you are in the app. When on an application, the route will be like `app.lenra.io/app/abcdef-1234-aaaa/` and no further routes will be added to this URL.

## Wanted Behavior

We want applications to define some navigation routes so that the user can use its hardware buttons to go back into the navigation system inside of the application. For example, if you are on `app.lenra.io/app/xxxx-xxxx-xxx/profile/settings` and you press the back button of your device, you will be redirected to `app.lenra.io/app/xxxx-xxxx-xxx/profile` instead of leaving the app.

## How to do it

- We cannot add a new GoRouter inside of the current GoRouter.
- The current GoRouter is final, can it be non final and can you add routes later when opening an app?
- The current GoRouter is used in the MaterialApp.router in the `main.dart`, can it be updated from another file such as a ChangeNotifier?

This PR [59](https://github.com/lenra-io/client/pull/59) shows that it is possible to modify the Router after it was instantiated. It just needs to reload all of the UI and it does not seem to keep the current state of the router after reloading it. 

It is difficult to navigate to the new routes directly after updating the Router because the whole context is dropped and a new one is created. This means that every call that were instantiated before this Router update will be unsuccessful because they will be using the wrong context.

Otherwise, it is easy to call the Router update first, wait for the UI to rebuild itself and then call a navigation event with the new context.

It is possible to set the `initialRoute` of the new `GoRouter` instance to fix this problem with the context. It will automatically redirect to this route when the GoRouter is updated.

#### Is it possible to match any route and all of its subroutes with GoRouter?

For example is it possible to match the `/app/example/` route and also all of its subroutes `/app/example/:subroute/:subroute/:etc...` ?

**Comment by taorepoara** [comment]
@jonas-martinez Can we close it ?
