### ISSUE TITLE
[Bug]: Build timeout

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/lenra_cli#195]
### What happened?

We should add a timeout to the build, set the status as a failure if the runner does not call back after 15 minutes.

**Comment by taorepoara** [comment]
@shiipou Does the new CI need a timeout or will the server be noticed of the state ?

**Comment by shiipou** [comment]
> @shiipou Does the new CI need a timeout or will the server be noticed of the state ?

The new CI use kubernetes callback (onSuccess and onFailure equivalent) to send notifications to the server to update the state.

So we need to add the timeout in case this notification was never received.
