### ISSUE TITLE
How to get app_uuid from app ? 

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#276]
I was wondering how to get the app_uuid directly from inside of an application. For example, if you want to trigger a webhook from the app, you need to have the app_uuid and webhook_uuid.

Either we need to have a way to get the app_uuid from the app (using the context for example) or we need to create a new route under the app pipe_through in application_runner specifically for triggering a webhook from inside of an application.

What do you think @lenra-io/devs ?

**Comment by jonas-martinez** [comment]
@pichoemr I needed to run a webhook directly from the application in one of my applications because this is the only way to run asynchronous code for the moment. 
In the future this might become useless as there will be new ways to do asynchronous code involving not calling a webhook.

**Comment by taorepoara** [comment]
You don't really need the uuid but just the webhook path that is returned when you create the webhook.

We should not have a case where the uuid is needed. 

By the way, nice way to run async listerners :smile:

**Comment by taorepoara** [comment]
I close this issue, but it can be reopened if we find another use case of having the app uuid.
