### ISSUE TITLE
[Bug]: Route have extra `/`

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/lenra_cli#282]
### What happened?

Lenra route have an extra `/`

### Relevant log output

```Shell
07:22:12.405 [info] JOINED route://map in 111ms
```

**Comment by taorepoara** [comment]
@pichoemr Is it resolved now ?

**Comment by jonas-martinez** [comment]
@pichoemr Can you add a more complete description of this issue ? (Where did you encounter the error ? client/devtool ?) How can we reproduce the issue?

It seems that I don't encounter this issue on my side.

**Comment by taorepoara** [comment]
Have been fixed
