### ISSUE TITLE
[Bug]: Command `lenra dev` didn't work on ARM64 devices

### ISSUE THREAD

**Issue by shiipou** [lenra-io/lenra_cli#292]
### What happened?

The mongodb image used with `lenra start`/`lenra dev` didn't include a working version for ARM64.
We need to find an alternative image for this architecture.

### What browsers are you seeing the problem on?

Other (specify above)

### Version

v1.0.0-beta.29

### Relevant log output

```Shell
Got something like PullBackoff Image
```

**Comment by taorepoara** [comment]
I'll try to find an image that working for all platforms (like the latest one does). It's strange since it seems to work on @Nesqwik computer

**Comment by taorepoara** [comment]
Migth be fixed by https://github.com/lenra-io/lenra_cli/pull/299

**Comment by shiipou** [comment]
@taorepoara After testing on Raspberry pi. This may work on ARMv8.2-A devices. On Raspberry, mongo version > 4.4.8 didn't support the device as seen on the logs when I start it. I can change the image in the generated `.lenra/docker-compose.yml` file and it seems to work with `docker-compose -f .lenra/docker-compose.yml up` command.

**Comment by taorepoara** [comment]
Ok, the solution is to use this version by adding the next lines at the end of the `lenra.yml` file in your project:

```yaml
dev:
  mongo:
    tag: 4.4.8
```
