### ISSUE TITLE
[Bug]: lenra build crash when there is no lenra.yml

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#30]
### What happened?

when i'm in a directory without the .lenra.yml file, the command lenra build crash instead of printing a useful error message.

### Version

lenra_cli 1.0.0-beta.5

### Relevant log output

```Shell
❯ lenra build
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/louis/.cargo/registry/src/github.com-1ecc6299db9ec823/lenra_cli-1.0.0-beta.5/src/config.rs:23:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by taorepoara** [comment]
Linked to #16 

I have added a comment to print a message when there is no file.

This one can be closed
