### ISSUE TITLE
[Bug]: localhost:4000 should not be automatically opened by the CLI

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#36]
### What happened?

I'm working on Windows with WSL, when I'm running `lenra start`, it opens `localhost:4000` inside of a WSL browser which can cause my computer to crash from time to time. This is an issue coming from WSL but we should not expect the CLI user to have a working browser. 

It would be better to just write in the console something like `The application is available at localhost:4000`.

What is your opinion on that @taorepoara ?

### Version

v1.0.0-beta.5

**Comment by taorepoara** [comment]
Yes, you're right. It also would resolve the new tab at every `lenra start` ^^

**Comment by taorepoara** [comment]
Resolved by #39
