### ISSUE TITLE
[Bug]: CLI stop when you make a command error

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/lenra_cli#59]
### What happened?

In the dev mod, when we make a command error (e.g. relaod instead of reload), the cli stops the application instead of writing an error message.

### Version

51-task-check-template-command

**Comment by taorepoara** [comment]
@pichoemr Can you try again in the same branch ?

I have added async/await and fixed some error handlings.

**Comment by pichoemr** [comment]
@taorepoara The problem is solved
