### ISSUE TITLE
[EPIC] Implement text search in Mongo queries

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#63]
Mongo provides a full-text search solution that can be really useful inside of Lenra applications when using search systems. For example, in the Tylen app, we need to implement a search component that can find users, messages, topics, etc...

This is really simple to implement and really well documented by Mongo. 
Here are some links that might be useful for this epic:

https://www.mongodb.com/docs/manual/core/text-search-operators/
https://www.mongodb.com/docs/manual/core/link-text-indexes/
https://www.digitalocean.com/community/tutorials/how-to-perform-full-text-search-in-mongodb

**Comment by pichoemr** [comment]
I'm closing this issue, replaced by https://github.com/lenra-io/lenra_cli/issues/188
