### ISSUE TITLE
[Bug]: The publication failed. I have no informations.

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#67]
### What happened?

- I go to dev.staging.lenra.io
- I go to the settings menu
- I change the URL of the git repository to `https://github.com/Nesqwik/suivi-jours.git`
- I go to "Overview"
- I click the Publish button
- My build fail. I don't know why.

### What browsers are you seeing the problem on?

Any

### Version

Staging, prod

**Comment by shiipou** [comment]
> @taorepoara It still fail [gitlab.com/lenra/platform/lenra-ci/-/pipelines/736200944](https://gitlab.com/lenra/platform/lenra-ci/-/pipelines/736200944)

After some investigations, it seems we didn't read the lenra.yml in the CI, so we need to before launching the dockerize job to know if we have to build a dockerfile or a dofigen config.

**Comment by taorepoara** [comment]
I'm changing the CI to make it use the `lenra build`. That way we'll have the same resulting Docker image.

**Comment by taorepoara** [comment]
@Nesqwik Can you retry ?
