### ISSUE TITLE
[Bug]: lenra build - Cache export feature is not supported for docker driver

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#8]
### What happened?

I created a new app using `lenra new node test` then i build it using `lenra build`

### Version

1.0.0-beta.1 (mac m1)

### Relevant log output

```Shell
❯ lenra build
[+] Building 0.0s (0/0)                                                                                                                               
error: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
thread 'main' panicked at 'An error occured while building the Docker image:

', src/build.rs:180:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Nesqwik** [comment]
Easy to fix, just run `docker buildx create --use`.
I just think it should be added to the doc first, maybe the CLI should config the docker buildx directly
I also think it could be better to cleanup the output log (clean log instead of crash)

**Comment by taorepoara** [comment]
Yes, I'll see to have a better error handling for later.

**Comment by taorepoara** [comment]
A better error handling has bin made
