### ISSUE TITLE
[EPIC] The Json view system

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#85]
The goal is to allow external app to connect to the realtime app.
- The app is created for two possible views : the "lenra" view and/or the "json" view.
- A view is represented using a route that can have params.
- The app define the views in the manifest.
- The client must connect to the app using the socket THEN connect to the views using the channels.
- Each channel is bind to a view. When the view change, the channel receive the updated view.

Example : 
I have a view that is defined in my manifest : 

```javascript
// [...]
{
    jsonRoutes: {
      "/todos": {
        "type": "widget",
        "name": "todosJson",
        "coll": "todos",
        "query": {
          "user": "@me",
        }
      },
      "/todos/:todoId": {
        "type": "widget",
        "name": "todoJson",
        "coll": "todos",
        "query": {
          "_id": "@route.todoId"
        }
    }
}
```

The first route `/todos` return the list of the todos and a listener to create a new one.
The second route `/todos/:todoId` return a specific todo with the listeners to toggle the checkbox and to delete it. 

The client can then : 
- create a new socket using `new Socket(url, {"app": appName})`
- create a new channel to send the listeners to the app using `socket.channel("listeners")`
- create a new channel to get the `/todos` view changes using `socket.channel("routes:/todos", {"mode": "json"})
- If the specific todo page is opened, create a new channel to get the `/todos/:todoId` changes using `socket.channel('routes:/todos/${todo._id}', {"mode", "json"})`

The work that need to be done : 
- [Update `application_runner` to implement the new system](https://github.com/lenra-io/application-runner/pull/242)
- [Update `lenra_ui_runner` to match the `application_runner` changes to the socket/channel system (but keep only one view)](https://github.com/lenra-io/lenra_ui_runner/issues/182)
- [Update `devtools` to use the new `application_runner` and `lenra_ui_runner`](https://github.com/lenra-io/dev-tools/pull/146)

Later :
- Update `application_runner` to make the `context` work with this new system.
- Update the `server` to use the new `application_runner` and `lenra_ui_runner`
- Update `lenra_ui_runner` to implement the route system bind to the url of the flutter route.

**Comment by taorepoara** [comment]
Managed by #209
