### ISSUE TITLE
[Bug]: Site Connection KeyPass

### ISSUE THREAD

**Issue by norphiil** [lenra-io/lenra_cli#91]
### What happened?

Lorsque je veux me connecter, les champs e-mail et mot de passe ne sont pas détectés par KeePass, puis lorsque je fais un clic droit, KeePass et que je fait saisir user et mdp, cela me donne cette erreur dans le terminal.

![image](https://user-images.githubusercontent.com/57914227/173193962-3a01b21b-b2ea-4dd7-a6d4-c305a86441e4.png)

Je ne sais pas si cela viens de keepass ou du site mais je préférer vous mettre au courant. 

Cordialement.

### What browsers are you seeing the problem on?

Firefox

### Version

101.0.1 (64 bits)

### Relevant log output

```Shell
Uncaught Error: RangeError (index): Index out of range: no indices are valid: 0
    d https://dev.lenra.io/main.dart.js:4825
    U https://dev.lenra.io/main.dart.js:37655
    a2g https://dev.lenra.io/main.dart.js:30879
    m1 https://dev.lenra.io/main.dart.js:30921
    $1 https://dev.lenra.io/main.dart.js:30852
    $1 https://dev.lenra.io/main.dart.js:30845
    aXY https://dev.lenra.io/main.dart.js:4906
    s https://dev.lenra.io/main.dart.js:4914
main.dart.js:4825:3
Uncaught Error: RangeError (index): Index out of range: no indices are valid: 0
    d https://dev.lenra.io/main.dart.js:4825
    U https://dev.lenra.io/main.dart.js:37655
    a2g https://dev.lenra.io/main.dart.js:30879
    m1 https://dev.lenra.io/main.dart.js:30921
    $1 https://dev.lenra.io/main.dart.js:30855
    $1 https://dev.lenra.io/main.dart.js:30845
    aXY https://dev.lenra.io/main.dart.js:4906
    s https://dev.lenra.io/main.dart.js:4914
main.dart.js:4825:3
```

**Comment by taorepoara** [comment]
Is it done ?

**Comment by shiipou** [comment]
Will be fixed by Oauth #209
